/** Auto-curated adult milestones from helper list — link-out only, 18+. */
export const ADULT_EXTRA_FETISH_TAGS: string[] = [
  "amateur",
  "casting",
  "cuckold",
  "gangbang",
  "hentai",
  "jav",
  "masturbating",
  "masturbation",
  "milf",
  "taboo",
  "voyeur",
  "vr",
]

export const ADULT_EXTRA_MILESTONES = [
  {
    name: 'CooMeet',
    href: 'https://coomeet.com/',
    copy: 'CooMeet — open externally (milestone / link-out).',
    group: 'cam',
    sourceId: 'coomeet',
  },
  {
    name: 'Flirtify',
    href: 'https://flirtify.com/',
    copy: 'Flirtify — open externally (milestone / link-out).',
    group: 'cam',
    sourceId: 'flirtify',
  },
  {
    name: 'LuckyCrush',
    href: 'https://luckycrush.live/',
    copy: 'LuckyCrush — open externally (milestone / link-out).',
    group: 'cam',
    sourceId: 'luckycrush',
  },
  {
    name: 'PornDudeGirls',
    href: 'https://porndudegirls.com/',
    copy: 'PornDudeGirls — open externally (milestone / link-out).',
    group: 'cam',
    sourceId: 'porndudegirls',
  },
  {
    name: 'Wife Bucket',
    href: 'https://www.wifebucket.com/',
    copy: 'Wife Bucket — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'wife-bucket',
  },
  {
    name: 'Exploited College Girls',
    href: 'https://www.exploitedcollegegirls.com/',
    copy: 'Exploited College Girls — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'exploited-college-girls',
  },
  {
    name: 'NetVideoGirls',
    href: 'https://netvideogirls.com/',
    copy: 'NetVideoGirls — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'netvideogirls',
  },
  {
    name: 'True Amateurs',
    href: 'https://www.trueamateurs.com/',
    copy: 'True Amateurs — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'true-amateurs',
  },
  {
    name: 'Backroom Casting Couch',
    href: 'https://backroomcastingcouch.com/',
    copy: 'Backroom Casting Couch — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'backroom-casting-couch',
  },
  {
    name: 'Czech Casting',
    href: 'https://czechcasting.com/',
    copy: 'Czech Casting — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'czech-casting',
  },
  {
    name: 'BangBus',
    href: 'https://bangbros.com/site/bangbus',
    copy: 'BangBus — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'bangbus',
  },
  {
    name: 'Private Society',
    href: 'https://www.privatesociety.com/',
    copy: 'Private Society — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'private-society',
  },
  {
    name: 'Woodman Casting X',
    href: 'https://www.woodmancastingx.com/',
    copy: 'Woodman Casting X — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'woodman-casting-x',
  },
  {
    name: 'LoveHomePorn',
    href: 'https://www.lovehomeporn.com/',
    copy: 'LoveHomePorn — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'lovehomeporn',
  },
  {
    name: 'VRPorn',
    href: 'https://vrporn.com/',
    copy: 'VRPorn — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'vrporn',
  },
  {
    name: 'POVR',
    href: 'https://www.povr.com/',
    copy: 'POVR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'povr',
  },
  {
    name: 'VirtualRealPorn',
    href: 'https://virtualrealporn.com/',
    copy: 'VirtualRealPorn — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'virtualrealporn',
  },
  {
    name: 'Naughty America VR',
    href: 'https://www.naughtyamericavr.com/',
    copy: 'Naughty America VR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'naughty-america-vr',
  },
  {
    name: 'BadoinkVR',
    href: 'https://badoinkvr.com/',
    copy: 'BadoinkVR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'badoinkvr',
  },
  {
    name: 'Virtual Taboo',
    href: 'https://virtualtaboo.com/',
    copy: 'Virtual Taboo — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'virtual-taboo',
  },
  {
    name: 'Dark Room VR',
    href: 'https://www.darkroomvr.com/',
    copy: 'Dark Room VR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'dark-room-vr',
  },
  {
    name: 'VRBangers',
    href: 'https://vrbangers.com/',
    copy: 'VRBangers — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'vrbangers',
  },
  {
    name: 'WankzVR',
    href: 'https://www.wankzvr.com/',
    copy: 'WankzVR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'wankzvr',
  },
  {
    name: 'AdultTime VR',
    href: 'https://adulttime.com/',
    copy: 'AdultTime VR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'adulttime-vr',
  },
  {
    name: 'FapHouse VR',
    href: 'https://faphouse.com/',
    copy: 'FapHouse VR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'faphouse-vr',
  },
  {
    name: 'Brazzers VR',
    href: 'https://www.brazzers.com/',
    copy: 'Brazzers VR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'brazzers-vr',
  },
  {
    name: 'CzechVR',
    href: 'https://www.czechvr.com/',
    copy: 'CzechVR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'czechvr',
  },
  {
    name: 'Virtual Porn',
    href: 'https://www.virtualporn.com/',
    copy: 'Virtual Porn — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'virtual-porn',
  },
  {
    name: 'MilfVR',
    href: 'https://www.milfvr.com/',
    copy: 'MilfVR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'milfvr',
  },
  {
    name: 'WetVR',
    href: 'https://www.wetvr.com/',
    copy: 'WetVR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'wetvr',
  },
  {
    name: 'VRHush',
    href: 'https://vrhush.com/',
    copy: 'VRHush — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'vrhush',
  },
  {
    name: 'VRCosplayX',
    href: 'https://www.vrcosplayx.com/',
    copy: 'VRCosplayX — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'vrcosplayx',
  },
  {
    name: 'VirtualRealJapan',
    href: 'https://virtualrealjapan.com/',
    copy: 'VirtualRealJapan — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'virtualrealjapan',
  },
  {
    name: 'XVirtual',
    href: 'https://www.xvirtual.com/',
    copy: 'XVirtual — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'xvirtual',
  },
  {
    name: 'SwallowBay',
    href: 'https://swallowbay.com/',
    copy: 'SwallowBay — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'swallowbay',
  },
  {
    name: '18VR',
    href: 'https://18vr.com/',
    copy: '18VR — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: '18vr',
  },
  {
    name: 'TmwVRnet',
    href: 'https://tmwvrnet.com/',
    copy: 'TmwVRnet — open externally (milestone / link-out).',
    group: 'vr',
    sourceId: 'tmwvrnet',
  },
  {
    name: 'Fapello',
    href: 'https://fapello.com/',
    copy: 'Fapello — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'fapello',
  },
  {
    name: 'SimpCity',
    href: 'https://simpcity.su/',
    copy: 'SimpCity — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'simpcity',
  },
  {
    name: 'PimpBunny',
    href: 'https://pimpbunny.com/',
    copy: 'PimpBunny — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'pimpbunny',
  },
  {
    name: 'Coomer Party',
    href: 'https://coomer.party/',
    copy: 'Coomer Party — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'coomer-party',
  },
  {
    name: 'LeakGallery',
    href: 'https://leakgallery.com/',
    copy: 'LeakGallery — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'leakgallery',
  },
  {
    name: 'MissAV',
    href: 'https://missav.ws/',
    copy: 'MissAV — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'missav',
  },
  {
    name: 'SupJav',
    href: 'https://supjav.com/',
    copy: 'SupJav — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'supjav',
  },
  {
    name: 'VJAV',
    href: 'https://vjav.com/',
    copy: 'VJAV — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'vjav',
  },
  {
    name: 'JavGuru',
    href: 'https://jav.guru/',
    copy: 'JavGuru — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'javguru',
  },
  {
    name: 'JAVMost',
    href: 'https://www5.javmost.com/',
    copy: 'JAVMost — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'javmost',
  },
  {
    name: 'KissJAV (ShyAV)',
    href: 'https://kissjav.com/',
    copy: 'KissJAV (ShyAV) — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'kissjav-shyav',
  },
  {
    name: '7MMTV',
    href: 'https://7mmtv.sx/',
    copy: '7MMTV — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: '7mmtv',
  },
  {
    name: 'BestJavPorn',
    href: 'https://www.bestjavporn.com/',
    copy: 'BestJavPorn — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'bestjavporn',
  },
  {
    name: 'JavBangers',
    href: 'https://www.javbangers.com/',
    copy: 'JavBangers — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'javbangers',
  },
  {
    name: '91Porn',
    href: 'https://91porn.com/',
    copy: '91Porn — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: '91porn',
  },
  {
    name: 'JAVHD.today',
    href: 'https://javhd.today/',
    copy: 'JAVHD.today — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'javhd-today',
  },
  {
    name: 'JAVGG',
    href: 'https://javgg.net/',
    copy: 'JAVGG — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'javgg',
  },
  {
    name: 'Javtiful',
    href: 'https://javtiful.com/',
    copy: 'Javtiful — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'javtiful',
  },
  {
    name: 'nJAV',
    href: 'https://njav.tv/',
    copy: 'nJAV — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'njav',
  },
  {
    name: 'Nutaku',
    href: 'https://www.nutaku.net/home/',
    copy: 'Nutaku — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'nutaku',
  },
  {
    name: 'Hentai Heroes',
    href: 'https://www.nutaku.net/games/hentai-heroes/',
    copy: 'Hentai Heroes — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'hentai-heroes',
  },
  {
    name: 'Lust Goddess',
    href: 'https://www.nutaku.net/',
    copy: 'Lust Goddess — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'lust-goddess',
  },
  {
    name: 'F95zone',
    href: 'https://f95zone.to/',
    copy: 'F95zone — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'f95zone',
  },
  {
    name: 'PornGamesHub',
    href: 'https://porngameshub.com/',
    copy: 'PornGamesHub — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'porngameshub',
  },
  {
    name: 'GamCore',
    href: 'https://gamcore.com/',
    copy: 'GamCore — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'gamcore',
  },
  {
    name: 'FAP Nation',
    href: 'https://fap-nation.com/',
    copy: 'FAP Nation — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'fap-nation',
  },
  {
    name: 'LewdZone',
    href: 'https://lewdzone.com/',
    copy: 'LewdZone — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'lewdzone',
  },
  {
    name: 'Itch.io NSFW',
    href: 'https://itch.io/games/free/nsfw',
    copy: 'Itch.io NSFW — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'itch-io-nsfw',
  },
  {
    name: 'Fenoxo',
    href: 'https://fenoxo.com/',
    copy: 'Fenoxo — open externally (milestone / link-out).',
    group: 'games',
    sourceId: 'fenoxo',
  },
  {
    name: 'MultPorn',
    href: 'https://multporn.net/',
    copy: 'MultPorn — open externally (milestone / link-out).',
    group: 'comic',
    sourceId: 'multporn',
  },
  {
    name: 'AllPornComic',
    href: 'https://allporncomic.com/',
    copy: 'AllPornComic — open externally (milestone / link-out).',
    group: 'comic',
    sourceId: 'allporncomic',
  },
  {
    name: '8Muses',
    href: 'https://8muses.io/',
    copy: '8Muses — open externally (milestone / link-out).',
    group: 'comic',
    sourceId: '8muses',
  },
  {
    name: 'Oglaf',
    href: 'https://www.oglaf.com/',
    copy: 'Oglaf — open externally (milestone / link-out).',
    group: 'comic',
    sourceId: 'oglaf',
  },
  {
    name: 'MilfNut',
    href: 'https://milfnut.com/',
    copy: 'MilfNut — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'milfnut',
  },
  {
    name: 'TabooTube',
    href: 'https://www.tabootube.xxx/',
    copy: 'TabooTube — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'tabootube',
  },
  {
    name: 'FamilyPornHD',
    href: 'https://familypornhd.com/',
    copy: 'FamilyPornHD — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'familypornhd',
  },
  {
    name: 'FamilyPorner',
    href: 'https://familyporner.com/',
    copy: 'FamilyPorner — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'familyporner',
  },
  {
    name: 'TabooDude',
    href: 'https://theporndude.com/',
    copy: 'TabooDude — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'taboodude',
  },
  {
    name: 'XVideos Taboo',
    href: 'https://www.xvideos.com/?k=taboo',
    copy: 'XVideos Taboo — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xvideos-taboo',
  },
  {
    name: 'SxyPrn Taboo',
    href: 'https://sxyprn.com/taboo',
    copy: 'SxyPrn Taboo — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'sxyprn-taboo',
  },
  {
    name: 'iXXX Taboo',
    href: 'https://www.ixxx.com/search/?q=taboo',
    copy: 'iXXX Taboo — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'ixxx-taboo',
  },
  {
    name: 'PornPics Taboo',
    href: 'https://www.pornpics.com/?q=taboo',
    copy: 'PornPics Taboo — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'pornpics-taboo',
  },
  {
    name: 'Scrolller Taboo',
    href: 'https://scrolller.com/search/taboo',
    copy: 'Scrolller Taboo — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'scrolller-taboo',
  },
  {
    name: 'ImageFap Taboo',
    href: 'https://www.imagefap.com/gallery.php?search=taboo',
    copy: 'ImageFap Taboo — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'imagefap-taboo',
  },
  {
    name: 'XVideos Gangbang',
    href: 'https://www.xvideos.com/?k=gangbang',
    copy: 'XVideos Gangbang — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xvideos-gangbang',
  },
  {
    name: 'PornHub GangBang',
    href: 'https://www.pornhub.com/video/search?search=gangbang',
    copy: 'PornHub GangBang — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'pornhub-gangbang',
  },
  {
    name: 'xHamster GangBang',
    href: 'https://xhamster.com/search/gangbang',
    copy: 'xHamster GangBang — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xhamster-gangbang',
  },
  {
    name: 'SpankBang GangBang',
    href: 'https://spankbang.com/s/gangbang/',
    copy: 'SpankBang GangBang — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'spankbang-gangbang',
  },
  {
    name: 'Eporner GangBang',
    href: 'https://www.eporner.com/search/gangbang/',
    copy: 'Eporner GangBang — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'eporner-gangbang',
  },
  {
    name: 'PornHub Cuckold',
    href: 'https://www.pornhub.com/video/search?search=cuckold',
    copy: 'PornHub Cuckold — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'pornhub-cuckold',
  },
  {
    name: 'xHamster Cuckold',
    href: 'https://xhamster.com/search/cuckold',
    copy: 'xHamster Cuckold — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xhamster-cuckold',
  },
  {
    name: 'XVideos Cuckold',
    href: 'https://www.xvideos.com/?k=cuckold',
    copy: 'XVideos Cuckold — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xvideos-cuckold',
  },
  {
    name: 'CuckoldsPorn',
    href: 'https://www.cuckoldsporn.com/',
    copy: 'CuckoldsPorn — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'cuckoldsporn',
  },
  {
    name: 'SpankBang Cuckold',
    href: 'https://spankbang.com/s/cuckold/',
    copy: 'SpankBang Cuckold — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'spankbang-cuckold',
  },
  {
    name: 'Eporner Cuckold',
    href: 'https://www.eporner.com/search/cuckold/',
    copy: 'Eporner Cuckold — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'eporner-cuckold',
  },
  {
    name: 'SxyPrn Cuckold',
    href: 'https://sxyprn.com/cuckold',
    copy: 'SxyPrn Cuckold — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'sxyprn-cuckold',
  },
  {
    name: 'XVideos Masturbation',
    href: 'https://www.xvideos.com/?k=masturbation',
    copy: 'XVideos Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xvideos-masturbation',
  },
  {
    name: 'PornHub Masturbation',
    href: 'https://www.pornhub.com/video/search?search=masturbation',
    copy: 'PornHub Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'pornhub-masturbation',
  },
  {
    name: 'xHamster Masturbation',
    href: 'https://xhamster.com/search/masturbation',
    copy: 'xHamster Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xhamster-masturbation',
  },
  {
    name: 'PornTrex Masturbation',
    href: 'https://www.porntrex.com/search/masturbation',
    copy: 'PornTrex Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'porntrex-masturbation',
  },
  {
    name: 'SxyPrn Masturbation',
    href: 'https://sxyprn.com/masturbation',
    copy: 'SxyPrn Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'sxyprn-masturbation',
  },
  {
    name: 'iXXX Masturbating',
    href: 'https://www.ixxx.com/search/?q=masturbating',
    copy: 'iXXX Masturbating — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'ixxx-masturbating',
  },
  {
    name: 'AlohaTube Masturbation',
    href: 'https://www.alohatube.com/search/masturbation',
    copy: 'AlohaTube Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'alohatube-masturbation',
  },
  {
    name: 'iWank Masturbation',
    href: 'https://www.iwank.tv/masturbation',
    copy: 'iWank Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'iwank-masturbation',
  },
  {
    name: 'PornPics Masturbation',
    href: 'https://www.pornpics.com/?q=masturbation',
    copy: 'PornPics Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'pornpics-masturbation',
  },
  {
    name: 'Scrolller Masturbation',
    href: 'https://scrolller.com/search/masturbation',
    copy: 'Scrolller Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'scrolller-masturbation',
  },
  {
    name: 'Sex.com Masturbation',
    href: 'https://www.sex.com/search?query=masturbation',
    copy: 'Sex.com Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'sex-com-masturbation',
  },
  {
    name: 'ImageFap Masturbation',
    href: 'https://www.imagefap.com/gallery.php?search=masturbation',
    copy: 'ImageFap Masturbation — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'imagefap-masturbation',
  },
  {
    name: 'XVideos Voyeur',
    href: 'https://www.xvideos.com/?k=voyeur',
    copy: 'XVideos Voyeur — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xvideos-voyeur',
  },
  {
    name: 'PornHub Voyeur',
    href: 'https://www.pornhub.com/video/search?search=voyeur',
    copy: 'PornHub Voyeur — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'pornhub-voyeur',
  },
  {
    name: 'xHamster Voyeur',
    href: 'https://xhamster.com/search/voyeur',
    copy: 'xHamster Voyeur — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'xhamster-voyeur',
  },
  {
    name: 'iXXX Voyeur',
    href: 'https://www.ixxx.com/search/?q=voyeur',
    copy: 'iXXX Voyeur — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'ixxx-voyeur',
  },
  {
    name: 'Scrolller Voyeur',
    href: 'https://scrolller.com/search/voyeur',
    copy: 'Scrolller Voyeur — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'scrolller-voyeur',
  },
  {
    name: 'PornPics Voyeur',
    href: 'https://www.pornpics.com/?q=voyeur',
    copy: 'PornPics Voyeur — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'pornpics-voyeur',
  },
  {
    name: 'Voyeur House Club',
    href: 'https://www.voyeurhouse.com/',
    copy: 'Voyeur House Club — open externally (milestone / link-out).',
    group: 'tube',
    sourceId: 'voyeur-house-club',
  },
  {
    name: 'eFukt',
    href: 'https://efukt.com/',
    copy: 'eFukt — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'efukt',
  },
  {
    name: 'XVideos Funny Porn',
    href: 'https://www.xvideos.com/?k=funny+porn',
    copy: 'XVideos Funny Porn — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'xvideos-funny-porn',
  },
  {
    name: 'PornHub Funny Porn',
    href: 'https://www.pornhub.com/video/search?search=funny+porn',
    copy: 'PornHub Funny Porn — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'pornhub-funny-porn',
  },
  {
    name: 'xHamster Funny Porn',
    href: 'https://xhamster.com/search/funny+porn',
    copy: 'xHamster Funny Porn — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'xhamster-funny-porn',
  },
  {
    name: 'XNXX Funny Porn',
    href: 'https://www.xnxx.com/search/funny+porn',
    copy: 'XNXX Funny Porn — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'xnxx-funny-porn',
  },
  {
    name: 'ImageFap Captions',
    href: 'https://www.imagefap.com/gallery.php?search=captions',
    copy: 'ImageFap Captions — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'imagefap-captions',
  },
  {
    name: 'Sex.com Captions',
    href: 'https://www.sex.com/search?query=captions',
    copy: 'Sex.com Captions — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'sex-com-captions',
  },
  {
    name: 'AcmeJoy',
    href: 'https://www.acmejoy.com/',
    copy: 'AcmeJoy — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'acmejoy',
  },
  {
    name: 'BestVibe',
    href: 'https://www.bestvibe.com/',
    copy: 'BestVibe — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'bestvibe',
  },
  {
    name: 'Adam & Eve Store',
    href: 'https://www.adameve.com/',
    copy: 'Adam & Eve Store — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'adam-eve-store',
  },
  {
    name: 'Fleshlight',
    href: 'https://www.fleshlight.com/',
    copy: 'Fleshlight — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'fleshlight',
  },
  {
    name: 'Tenga',
    href: 'https://www.tenga.co.jp/',
    copy: 'Tenga — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'tenga',
  },
  {
    name: 'Lovense',
    href: 'https://www.lovense.com/',
    copy: 'Lovense — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'lovense',
  },
  {
    name: 'The Handy Feeling',
    href: 'https://www.thehandy.com/',
    copy: 'The Handy Feeling — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'the-handy-feeling',
  },
  {
    name: 'Kiiroo',
    href: 'https://www.kiiroo.com/',
    copy: 'Kiiroo — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'kiiroo',
  },
  {
    name: 'BathMate Direct',
    href: 'https://www.bathmatedirect.com/',
    copy: 'BathMate Direct — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'bathmate-direct',
  },
  {
    name: 'The Enhanced Male',
    href: 'https://www.enhancedmale.com/',
    copy: 'The Enhanced Male — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'the-enhanced-male',
  },
  {
    name: 'MrSkin',
    href: 'https://www.mrskin.com/',
    copy: 'MrSkin — open externally (milestone / link-out).',
    group: 'directory',
    sourceId: 'mrskin',
  },
  {
    name: 'GoneWild',
    href: 'https://www.reddit.com/r/gonewild/',
    copy: 'GoneWild — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'gonewild',
  },
  {
    name: 'NSFW',
    href: 'https://www.reddit.com/r/nsfw/',
    copy: 'NSFW — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'nsfw',
  },
  {
    name: 'Reddit NSFW GIF',
    href: 'https://www.reddit.com/r/NSFW_GIF/',
    copy: 'Reddit NSFW GIF — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-nsfw-gif',
  },
  {
    name: 'Reddit Real Girls',
    href: 'https://www.reddit.com/r/RealGirls/',
    copy: 'Reddit Real Girls — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-real-girls',
  },
  {
    name: 'JizzedToThis',
    href: 'https://www.reddit.com/r/JizzedToThis/',
    copy: 'JizzedToThis — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'jizzedtothis',
  },
  {
    name: 'Hold The Moan',
    href: 'https://www.reddit.com/r/HoldTheMoan/',
    copy: 'Hold The Moan — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'hold-the-moan',
  },
  {
    name: 'Reddit Busty Petite',
    href: 'https://www.reddit.com/r/BustyPetite/',
    copy: 'Reddit Busty Petite — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-busty-petite',
  },
  {
    name: 'Reddit CumSluts',
    href: 'https://www.reddit.com/r/cumsluts/',
    copy: 'Reddit CumSluts — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-cumsluts',
  },
  {
    name: 'PetiteGoneWild',
    href: 'https://www.reddit.com/r/PetiteGoneWild/',
    copy: 'PetiteGoneWild — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'petitegonewild',
  },
  {
    name: 'Sex',
    href: 'https://www.reddit.com/r/sex/',
    copy: 'Sex — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'sex',
  },
  {
    name: 'Reddit TikTokThots',
    href: 'https://www.reddit.com/r/TikTokThots/',
    copy: 'Reddit TikTokThots — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-tiktokthots',
  },
  {
    name: 'Reddit Mature Milf',
    href: 'https://www.reddit.com/r/maturemilf/',
    copy: 'Reddit Mature Milf — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-mature-milf',
  },
  {
    name: 'Adorable Porn',
    href: 'https://www.reddit.com/r/adorableporn/',
    copy: 'Adorable Porn — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'adorable-porn',
  },
  {
    name: 'Reddit NSFW GIFS',
    href: 'https://www.reddit.com/r/nsfw_gifs/',
    copy: 'Reddit NSFW GIFS — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-nsfw-gifs',
  },
  {
    name: 'God Pussy',
    href: 'https://www.reddit.com/r/GodPussy/',
    copy: 'God Pussy — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'god-pussy',
  },
  {
    name: 'Reddit AsiansGoneWild',
    href: 'https://www.reddit.com/r/AsiansGoneWild/',
    copy: 'Reddit AsiansGoneWild — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-asiansgonewild',
  },
  {
    name: 'Reddit GirlsFinishingTheJob',
    href: 'https://www.reddit.com/r/GirlsFinishingTheJob/',
    copy: 'Reddit GirlsFinishingTheJob — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-girlsfinishingthejob',
  },
  {
    name: 'Reddit Rule 34',
    href: 'https://www.reddit.com/r/rule34/',
    copy: 'Reddit Rule 34 — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-rule-34',
  },
  {
    name: 'Reddit Public',
    href: 'https://www.reddit.com/r/Public/',
    copy: 'Reddit Public — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-public',
  },
  {
    name: 'Reddit College Sluts',
    href: 'https://www.reddit.com/r/collegesluts/',
    copy: 'Reddit College Sluts — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-college-sluts',
  },
  {
    name: 'Reddit Amateur',
    href: 'https://www.reddit.com/r/Amateur/',
    copy: 'Reddit Amateur — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-amateur',
  },
  {
    name: 'Reddit Hentai',
    href: 'https://www.reddit.com/r/hentai/',
    copy: 'Reddit Hentai — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-hentai',
  },
  {
    name: 'Reddit Bigger Than You Thought',
    href: 'https://www.reddit.com/r/BiggerThanYouThought/',
    copy: 'Reddit Bigger Than You Thought — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-bigger-than-you-thought',
  },
  {
    name: 'Mom Bod',
    href: 'https://www.reddit.com/r/MomBod/',
    copy: 'Mom Bod — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'mom-bod',
  },
  {
    name: 'Reddit Small Cutie',
    href: 'https://www.reddit.com/r/SmallCutie/',
    copy: 'Reddit Small Cutie — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-small-cutie',
  },
  {
    name: 'Reddit Tip Of My Penis',
    href: 'https://www.reddit.com/r/TipOfMyPenis/',
    copy: 'Reddit Tip Of My Penis — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-tip-of-my-penis',
  },
  {
    name: 'Reddit MassiveTitsnAss',
    href: 'https://www.reddit.com/r/MassiveTitsNAss/',
    copy: 'Reddit MassiveTitsnAss — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-massivetitsnass',
  },
  {
    name: 'Reddit Titty Drop',
    href: 'https://www.reddit.com/r/tittydrop/',
    copy: 'Reddit Titty Drop — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-titty-drop',
  },
  {
    name: 'Reddit Porn In Fifteen Seconds',
    href: 'https://www.reddit.com/r/porninfifteenseconds/',
    copy: 'Reddit Porn In Fifteen Seconds — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'reddit-porn-in-fifteen-seconds',
  },
  {
    name: 'JustFriendsHavingFun',
    href: 'https://www.reddit.com/r/JustFriendsHavingFun/',
    copy: 'JustFriendsHavingFun — open externally (milestone / link-out).',
    group: 'community',
    sourceId: 'justfriendshavingfun',
  },
] as const;
