/** Adult fetish / category chips. Featured first; includes every Pornhub category + languages. */

export const ADULT_FEATURED_FETISH_TAGS = [
  'milf',
  'double penetration',
  'dp',
  'role play',
  'roleplay',
  'feet',
  'anal',
  'lesbian',
  'gangbang',
  'cuckold',
  'cosplay',
  'step fantasy',
  'latina',
  'asian',
  'ebony',
  'bbw',
  'hentai',
  'vr',
  'webcam',
] as const;

const ADULT_CATALOG_FETISH_TAGS = [
  'ebony',
  'bbw',
  'solo female',
  'big dick',
  'masturbation',
  'transgender',
  'pornstar',
  'exclusive',
  'interracial',
  'small tits',
  '18-25',
  '60fps',
  'ai',
  'amateur',
  'anal',
  'arab',
  'asian',
  'babe',
  'babysitter (18+)',
  'behind the scenes',
  'big ass',
  'big tits',
  'bisexual male',
  'blonde',
  'blowjob',
  'bondage',
  'brazilian',
  'british',
  'brunette',
  'bukkake',
  'cartoon',
  'casting',
  'celebrity',
  'closed captions',
  'college (18+)',
  'compilation',
  'cosplay',
  'creampie',
  'cuckold',
  'cumshot',
  'czech',
  'deepthroat',
  'described video',
  'double penetration',
  'euro',
  'feet',
  'female orgasm',
  'fetish',
  'fingering',
  'fisting',
  'french',
  'funny',
  'gaming',
  'gangbang',
  'german',
  'handjob',
  'hardcore',
  'hd porn',
  'hentai',
  'indian',
  'interactive',
  'italian',
  'japanese',
  'korean',
  'latina',
  'lesbian',
  'massage',
  'mature',
  'milf',
  'muscular men',
  'music',
  'old/young (18+)',
  'orgy',
  'parody',
  'party',
  'pissing',
  'podcast',
  'popular with women',
  'pov',
  'public',
  'pussy licking',
  'reaction',
  'reality',
  'red head',
  'role play',
  'romantic',
  'rough sex',
  'russian',
  'school (18+)',
  'sfw',
  'smoking',
  'solo male',
  'squirt',
  'step fantasy',
  'strap on',
  'striptease',
  'tattooed women',
  'threesome',
  'toys',
  'verified amateurs',
  'verified couples',
  'verified models',
  'vintage',
  'virtual reality',
  'webcam',
  'spanish',
  'arabic',
  'portuguese',
  'tagalog',
  'thai',
  'ukrainian',
  'polish',
  'dutch',
  'hindi',
  'chinese',
  'persian',
  'dp',
  'roleplay',
  'vr',
  'thruple',
  'manhwa',
  'taboo',
  'celeb',
  'bdsm',
  'femdom',
  'jav',
  'pawg',
  'pegging',
  'joi',
  'bbc',
] as const;

function uniqueLower(values: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of values) {
    const tag = raw.trim().toLowerCase();
    if (tag.length < 2 || seen.has(tag)) continue;
    seen.add(tag);
    out.push(tag);
  }
  return out;
}

/** Featured first, then the rest of the catalog (stable, de-duped). */
export const ADULT_CURATED_FETISH_TAGS: string[] = uniqueLower([
  ...ADULT_FEATURED_FETISH_TAGS,
  ...ADULT_CATALOG_FETISH_TAGS,
]);

/** Keyword pages used when browsing "all" so shelves get richer fetish coverage. */
export const ADULT_DEEPEN_FETISH_QUERIES: string[] = uniqueLower([
  'milf',
  'double penetration',
  'role play',
  'feet',
  'anal',
  'lesbian',
  'gangbang',
  'cuckold',
  'cosplay',
  'step fantasy',
  'latina',
  'asian',
  'ebony',
  'bbw',
  'hentai',
  'vr',
  'webcam',
  'creampie',
  'amateur',
  'threesome',
  'bondage',
  'pov',
  'japanese',
]);

const FETISH_SEARCH_ALIASES: Record<string, string> = {
  'dp': 'double penetration',
  'roleplay': 'role play',
  'role play': 'role play',
  'vr': 'virtual reality',
  'virtual reality': 'vr',
  'red head': 'redhead',
  'strap on': 'strap on',
  'transgender': 'trans',
  'thruple': 'threesome',
  'celeb': 'celebrity',
  'babysitter (18+)': 'babysitter',
  'college (18+)': 'college',
  'school (18+)': 'school 18',
  'old/young (18+)': 'old young',
  'solo female': 'solo female',
  'solo male': 'solo male',
  'hd porn': 'hd',
  '18-25': '18-25',
};

export function fetishSearchQuery(tag: string): string {
  const clean = tag.trim().toLowerCase();
  return FETISH_SEARCH_ALIASES[clean] ?? clean;
}
