/** Niche / feet / cosplay / celeb / manhwa milestones — link-out only, 18+. Skip revenge-porn leak sites. */
export const ADULT_NICHE_MILESTONES = [
  {
    name: 'PornDude AI',
    href: 'https://theporndude.com/ai-porn',
    copy: 'PornDude AI — open externally (milestone / link-out).',
    group: 'review',
    sourceId: 'porndude-ai',
  },
  {
    name: 'Hentai Sites hub',
    href: 'https://theporndude.com/hentai-sites',
    copy: 'Hentai Sites hub — open externally (milestone / link-out).',
    group: 'review',
    sourceId: 'porndude-hentai',
  },
  {
    name: 'BestPornGames',
    href: 'https://bestporngames.com/',
    copy: 'BestPornGames — open externally (milestone / link-out).',
    group: 'review',
    sourceId: 'bestporngames',
  },
  {
    name: 'TPD Deals',
    href: 'https://theporndude.com/deals',
    copy: 'TPD Deals — open externally (milestone / link-out).',
    group: 'review',
    sourceId: 'tpd-deals',
  },
  {
    name: 'MyGaySites',
    href: 'https://mygaysites.com/',
    copy: 'MyGaySites — open externally (milestone / link-out).',
    group: 'review',
    sourceId: 'mygaysites',
  },
  {
    name: 'Porn Webmasters',
    href: 'https://theporndude.com/porn-webmasters',
    copy: 'Porn Webmasters — open externally (milestone / link-out).',
    group: 'review',
    sourceId: 'porn-webmasters',
  },
  {
    name: 'RealLifeCam',
    href: 'https://reallifecam.com/',
    copy: 'RealLifeCam — open externally (milestone / link-out).',
    group: 'voyeur',
    sourceId: 'reallifecam',
  },
  {
    name: 'Voyeur House TV',
    href: 'https://www.voyeurhouse.com/',
    copy: 'Voyeur House TV — open externally (milestone / link-out).',
    group: 'voyeur',
    sourceId: 'voyeur-house-tv',
  },
  {
    name: 'CamSoda Voyeur',
    href: 'https://www.camsoda.com/tags/voyeur',
    copy: 'CamSoda Voyeur — open externally (milestone / link-out).',
    group: 'voyeur',
    sourceId: 'camsoda-voyeur',
  },
  {
    name: 'StripChat Spy Shows',
    href: 'https://stripchat.com/tags/spy',
    copy: 'StripChat Spy Shows — open externally (milestone / link-out).',
    group: 'voyeur',
    sourceId: 'stripchat-spy',
  },
  {
    name: 'BongaCams Spy Shows',
    href: 'https://bongacams.com/',
    copy: 'BongaCams Spy Shows — open externally (milestone / link-out).',
    group: 'voyeur',
    sourceId: 'bongacams-spy',
  },
  {
    name: 'ThePornDude Blog',
    href: 'https://theporndude.com/blog',
    copy: 'ThePornDude Blog — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'porndude-blog',
  },
  {
    name: 'DampLips',
    href: 'https://damplips.com/',
    copy: 'DampLips — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'damplips',
  },
  {
    name: 'Bdsmlr',
    href: 'https://bdsmlr.com/',
    copy: 'Bdsmlr — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'bdsmlr',
  },
  {
    name: 'Phun.org',
    href: 'https://www.phun.org/',
    copy: 'Phun.org — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'phun',
  },
  {
    name: 'xMissy',
    href: 'https://www.xmissy.nl/',
    copy: 'xMissy — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'xmissy',
  },
  {
    name: 'SexyAndFunny',
    href: 'https://www.sexyandfunny.com/',
    copy: 'SexyAndFunny — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'sexyandfunny',
  },
  {
    name: 'AlRincon',
    href: 'https://www.alrincon.com/',
    copy: 'AlRincon — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'alrincon',
  },
  {
    name: 'URLGalleries',
    href: 'https://www.urlgalleries.net/',
    copy: 'URLGalleries — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'urlgalleries',
  },
  {
    name: 'Fleshbot',
    href: 'https://www.fleshbot.com/',
    copy: 'Fleshbot — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'fleshbot',
  },
  {
    name: 'RussiaSexyGirls',
    href: 'https://russiasexygirls.com/',
    copy: 'RussiaSexyGirls — open externally (milestone / link-out).',
    group: 'blog',
    sourceId: 'russiasexygirls',
  },
  {
    name: 'AI Smut Writer',
    href: 'https://aisumutwriter.com/',
    copy: 'AI Smut Writer — open externally (milestone / link-out).',
    group: 'ai',
    sourceId: 'ai-smut-writer',
  },
  {
    name: 'MySpicyVanilla',
    href: 'https://www.myspicyvanilla.com/',
    copy: 'MySpicyVanilla — open externally (milestone / link-out).',
    group: 'ai',
    sourceId: 'myspicyvanilla',
  },
  {
    name: 'NovelX',
    href: 'https://novelx.ai/',
    copy: 'NovelX — open externally (milestone / link-out).',
    group: 'ai',
    sourceId: 'novelx',
  },
  {
    name: 'CrazyShit',
    href: 'https://www.crazyshit.com/',
    copy: 'CrazyShit — open externally (milestone / link-out).',
    group: 'extreme',
    sourceId: 'crazyshit',
  },
  {
    name: 'DarknessPorn',
    href: 'https://www.darknessporn.com/',
    copy: 'DarknessPorn — open externally (milestone / link-out).',
    group: 'extreme',
    sourceId: 'darknessporn',
  },
  {
    name: 'XVideos Horror',
    href: 'https://www.xvideos.com/?k=horror',
    copy: 'XVideos Horror — open externally (milestone / link-out).',
    group: 'extreme',
    sourceId: 'xvideos-horror',
  },
  {
    name: 'PornHub Horror',
    href: 'https://www.pornhub.com/video/search?search=horror',
    copy: 'PornHub Horror — open externally (milestone / link-out).',
    group: 'extreme',
    sourceId: 'pornhub-horror',
  },
  {
    name: 'Scrolller Weird Porn',
    href: 'https://scrolller.com/',
    copy: 'Scrolller Weird Porn — open externally (milestone / link-out).',
    group: 'extreme',
    sourceId: 'scrolller-weird',
  },
  {
    name: 'Literotica Horror',
    href: 'https://www.literotica.com/c/horror-erotica',
    copy: 'Literotica Horror — open externally (milestone / link-out).',
    group: 'extreme',
    sourceId: 'literotica-horror',
  },
  {
    name: 'NaughtyBlog',
    href: 'https://www.naughtyblog.org/',
    copy: 'NaughtyBlog — link-out only (no in-app downloader or torrent client).',
    group: 'download',
    sourceId: 'naughtyblog',
  },
  {
    name: '0XXX',
    href: 'https://0xxx.ws/',
    copy: '0XXX — link-out only (no in-app downloader or torrent client).',
    group: 'download',
    sourceId: '0xxx',
  },
  {
    name: 'XXXStreams',
    href: 'https://xxxstreams.org/',
    copy: 'XXXStreams — link-out only (no in-app downloader or torrent client).',
    group: 'download',
    sourceId: 'xxxstreams',
  },
  {
    name: 'JavLibrary',
    href: 'https://www.javlibrary.com/',
    copy: 'JavLibrary — link-out only (no in-app downloader or torrent client).',
    group: 'download',
    sourceId: 'javlibrary',
  },
  {
    name: 'MaxJAV',
    href: 'https://maxjav.com/',
    copy: 'MaxJAV — link-out only (no in-app downloader or torrent client).',
    group: 'download',
    sourceId: 'maxjav',
  },
  {
    name: 'HotPornFile',
    href: 'https://www.hotpornfile.org/',
    copy: 'HotPornFile — link-out only (no in-app downloader or torrent client).',
    group: 'download',
    sourceId: 'hotpornfile',
  },
  {
    name: 'Keep2Porn',
    href: 'https://keep2porn.com/',
    copy: 'Keep2Porn — link-out only (no in-app downloader or torrent client).',
    group: 'download',
    sourceId: 'keep2porn',
  },
  {
    name: 'The Pirate Bay',
    href: 'https://thepiratebay.org/',
    copy: 'The Pirate Bay — link-out only (no in-app downloader or torrent client).',
    group: 'torrent',
    sourceId: 'thepiratebay',
  },
  {
    name: '1337x',
    href: 'https://1337x.to/',
    copy: '1337x — link-out only (no in-app downloader or torrent client).',
    group: 'torrent',
    sourceId: '1337x',
  },
  {
    name: 'Sukebei Nyaa',
    href: 'https://sukebei.nyaa.si/',
    copy: 'Sukebei Nyaa — link-out only (no in-app downloader or torrent client).',
    group: 'torrent',
    sourceId: 'sukebei-nyaa',
  },
  {
    name: 'OneJAV',
    href: 'https://onejav.com/',
    copy: 'OneJAV — link-out only (no in-app downloader or torrent client).',
    group: 'torrent',
    sourceId: 'onejav',
  },
  {
    name: 'Tokyo Toshokan',
    href: 'https://www.tokyotosho.info/',
    copy: 'Tokyo Toshokan — link-out only (no in-app downloader or torrent client).',
    group: 'torrent',
    sourceId: 'tokyo-toshokan',
  },
  {
    name: 'PornHub Feet',
    href: 'https://www.pornhub.com/video/search?search=feet',
    copy: 'PornHub Feet — open externally (milestone / link-out).',
    group: 'feet',
    sourceId: 'pornhub-feet',
  },
  {
    name: 'XVideos Feet',
    href: 'https://www.xvideos.com/?k=feet',
    copy: 'XVideos Feet — open externally (milestone / link-out).',
    group: 'feet',
    sourceId: 'xvideos-feet',
  },
  {
    name: 'xHamster Feet',
    href: 'https://xhamster.com/search/feet',
    copy: 'xHamster Feet — open externally (milestone / link-out).',
    group: 'feet',
    sourceId: 'xhamster-feet',
  },
  {
    name: 'Feet9',
    href: 'https://www.feet9.com/',
    copy: 'Feet9 — open externally (milestone / link-out).',
    group: 'feet',
    sourceId: 'feet9',
  },
  {
    name: 'FootStockings',
    href: 'https://www.footstockings.com/',
    copy: 'FootStockings — open externally (milestone / link-out).',
    group: 'feet',
    sourceId: 'footstockings',
  },
  {
    name: 'wikiFeet',
    href: 'https://www.wikifeet.com/',
    copy: 'wikiFeet — open externally (milestone / link-out).',
    group: 'feet',
    sourceId: 'wikifeet-db',
  },
  {
    name: 'Eporner Footjob',
    href: 'https://www.eporner.com/search/footjob/',
    copy: 'Eporner Footjob — open externally (milestone / link-out).',
    group: 'feet',
    sourceId: 'eporner-footjob',
  },
  {
    name: 'AZNude Feet',
    href: 'https://www.aznude.com/',
    copy: 'AZNude Feet — open externally (milestone / link-out).',
    group: 'feet',
    sourceId: 'aznude-feet',
  },
  {
    name: 'PornHub Cosplay',
    href: 'https://www.pornhub.com/video/search?search=cosplay',
    copy: 'PornHub Cosplay — open externally (milestone / link-out).',
    group: 'cosplay',
    sourceId: 'pornhub-cosplay',
  },
  {
    name: 'VRCosplayX',
    href: 'https://www.vrcosplayx.com/',
    copy: 'VRCosplayX — open externally (milestone / link-out).',
    group: 'cosplay',
    sourceId: 'vrcosplayx-hub',
  },
  {
    name: 'Eporner Cosplay',
    href: 'https://www.eporner.com/search/cosplay/',
    copy: 'Eporner Cosplay — open externally (milestone / link-out).',
    group: 'cosplay',
    sourceId: 'eporner-cosplay',
  },
  {
    name: 'AZNude',
    href: 'https://www.aznude.com/',
    copy: 'AZNude — open externally (milestone / link-out).',
    group: 'celeb',
    sourceId: 'aznude',
  },
  {
    name: 'Nudography',
    href: 'https://www.nudography.com/',
    copy: 'Nudography — open externally (milestone / link-out).',
    group: 'celeb',
    sourceId: 'nudography',
  },
  {
    name: 'MrSkin',
    href: 'https://www.mrskin.com/',
    copy: 'MrSkin — open externally (milestone / link-out).',
    group: 'celeb',
    sourceId: 'mrskin-celeb',
  },
  {
    name: 'Toomics',
    href: 'https://toomics.com/',
    copy: 'Toomics — open externally (milestone / link-out).',
    group: 'manhwa',
    sourceId: 'toomics',
  },
  {
    name: 'Eporner Manhwa',
    href: 'https://www.eporner.com/search/manhwa/',
    copy: 'Eporner Manhwa — open externally (milestone / link-out).',
    group: 'manhwa',
    sourceId: 'eporner-manhwa',
  },
  {
    name: 'PornHub Hentai Comics',
    href: 'https://www.pornhub.com/video/search?search=manhwa',
    copy: 'PornHub Hentai Comics — open externally (milestone / link-out).',
    group: 'manhwa',
    sourceId: 'pornhub-manhwa',
  },
] as const;
