/** Curated public X handles for one-time Adults / Social seeding (18+). */
export const X_ADULT_SEED_HANDLES: string[] = [
  "ThePornDude",
  "Brazzers",
  "Pornhub",
  "MiaMalkova",
  "soogsx",
  "Amouranth",
  "KittyxKum",
  "RileyReid",
  "EsperanzaGomez",
  "SophieRainx",
  "AngelaWhite",
  "puppiwi",
  "belle_delphine",
  "Abella_Danger",
  "Vladislava_",
  "RealityPornKing",
  "EmarrB",
  "BaybeKimchi",
  "BrittanyaRazavi",
  "BishoujoMom",
  "TheLisaAnn",
  "BambiDoe",
  "miakhalifa",
  "TeannaTrump",
  "AndiiPoops",
  "GiselleMontesX",
  "Playboy",
  "PurpleBitch1",
  "SashaGrey",
  "JennaLynnMeowri",
  "AlinaRoseASMR",
  "WaifuMia",
].map((h) => h.replace(/^@/, "").toLowerCase()).filter((h) => /^[a-z0-9_]{1,15}$/.test(h));
