/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNetworkPresenceRouteImport } from './routes/api/network-presence'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkPresenceRoute = ApiNetworkPresenceRouteImport.update({
  id: '/api/network-presence',
  path: '/api/network-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/network-presence': typeof ApiNetworkPresenceRoute
  '/api/rtc': typeof ApiRtcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/network-presence': typeof ApiNetworkPresenceRoute
  '/api/rtc': typeof ApiRtcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/network-presence': typeof ApiNetworkPresenceRoute
  '/api/rtc': typeof ApiRtcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/network-presence' | '/api/rtc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/network-presence' | '/api/rtc'
  id: '__root__' | '/' | '/api/network-presence' | '/api/rtc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiNetworkPresenceRoute: typeof ApiNetworkPresenceRoute
  ApiRtcRoute: typeof ApiRtcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network-presence': {
      id: '/api/network-presence'
      path: '/api/network-presence'
      fullPath: '/api/network-presence'
      preLoaderRoute: typeof ApiNetworkPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiNetworkPresenceRoute: ApiNetworkPresenceRoute,
  ApiRtcRoute: ApiRtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
